#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: Dec 14th, 2014
# -----------------------------------------------------------------------------


if [ ! -f /data/spigot.jar ]
then
    wget "http://158.69.193.93/download_template.php?pass=JollyJoe123&template=lb" -o /data/luckyblocks.tar
    tar xvf /data/luckyblocks.tar
    rm -rf /data/luckyblocks.tar
fi

cd /data/; java -Xmx1G -Xms1G -jar spigot.jar

